If we bind to loopback, then outbound sends fail
in ddht/datagram.py at method send_datagram() with:
OSError: [Errno 22] Invalid argument

As best I can tell, it's because Linux prevents outbound messages to
anything but loopback if you bind to 127.0.0.1. This is mentioned
tangentially in:
https://stackoverflow.com/a/8441679/8412986